### ISSUE TITLE
get_data_distribution 函数调用报错

### ISSUE THREAD

**Issue by zengqingshun** [stat-fit/westat#1]
调用get_data_distribution的时候报错
python3.10

26行 : df_ratio['%Ratio'] = df_ratio[col] / len(data)
修改为  df_ratio['%Ratio'] = df_ratio['count'] / len(data)

30行：df_ratio = df_ratio.rename(columns={col: '#Count'})
修改为: df_ratio = df_ratio.rename(columns={'count': '#Count'})

本地环境测试编译通过

**Comment by zengqingshun** [comment]
我自己在windows下测试有 python 3.10，没问题

之前是在Linux下测试 python3.10的，估计是环境问题

**Comment by stat-fit** [comment]
感谢反馈

**Comment by stat-fit** [comment]
在版本0.1.15中已经修复了该错误，请知悉！
